# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import pkg_resources
import subprocess
import sphinx_multiversion
sys.path.insert(0, os.path.abspath('..'))


# -- Project information -----------------------------------------------------

project = 'pymycqu'
copyright = '2021, Hagb'
author = 'Hagb'
# The full version, including alpha/beta/rc tags

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

extensions = ["sphinx.ext.autodoc", "sphinx.ext.autosummary", "sphinx_multiversion"]
html_sidebars = {'**': ['localtoc.html', 'relations.html', 'sourcelink.html', 'searchbox.html', 'versioning.html']}

if not hasattr(sphinx_multiversion.sphinx, "config_inited_hooked"):
    old_config_inited = sphinx_multiversion.sphinx.config_inited
    def config_inited(app, config):
        old_config_inited(app, config)
        config.release = config.smv_current_version
    sphinx_multiversion.sphinx.config_inited = config_inited
    sphinx_multiversion.sphinx.config_inited_hooked = True

smv_tag_whitelist = r'^v\d+.*$'
smv_branch_whitelist = r'^master|dev$'
smv_remote_whitelist = None

#autodoc_default_flags = ['members', 'attributes']
autosummary_generate = True
autosummary_ignore_module_all = False
#autosummary_imported_members = True
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
html_theme = "classic"
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

